java_library(
   name='reservation',
   sources=globs('*.java'),
   dependencies=[
       '3rdparty/jvm/com/fasterxml/jackson:jackson-core',
       '3rdparty/jvm/com/fasterxml/jackson:jackson-annotations',
   ]
)
